# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.networkanalysis import networkanalysis_pb2 as proto_dot_networkanalysis_dot_networkanalysis__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/networkanalysis/networkanalysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NetworkAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolveMatrix = channel.unary_unary(
                '/networkanalysis.NetworkAnalyzer/SolveMatrix',
                request_serializer=proto_dot_networkanalysis_dot_networkanalysis__pb2.MatrixData.SerializeToString,
                response_deserializer=proto_dot_networkanalysis_dot_networkanalysis__pb2.SolutionResponse.FromString,
                _registered_method=True)


class NetworkAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SolveMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SolveMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.SolveMatrix,
                    request_deserializer=proto_dot_networkanalysis_dot_networkanalysis__pb2.MatrixData.FromString,
                    response_serializer=proto_dot_networkanalysis_dot_networkanalysis__pb2.SolutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'networkanalysis.NetworkAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NetworkAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SolveMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/networkanalysis.NetworkAnalyzer/SolveMatrix',
            proto_dot_networkanalysis_dot_networkanalysis__pb2.MatrixData.SerializeToString,
            proto_dot_networkanalysis_dot_networkanalysis__pb2.SolutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
