# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/networkanalysis/networkanalysis.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+proto/networkanalysis/networkanalysis.proto\x12\x0fnetworkanalysis\"j\n\nMatrixData\x12\x0e\n\x06matrix\x18\x01 \x03(\x01\x12\x0e\n\x06vector\x18\x02 \x03(\x01\x12\x13\n\x0bmatrix_rows\x18\x03 \x01(\x05\x12\x13\n\x0bmatrix_cols\x18\x04 \x01(\x05\x12\x12\n\ntarget_idx\x18\x05 \x01(\x05\"D\n\x10SolutionResponse\x12\x10\n\x08solution\x18\x01 \x03(\x01\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t2b\n\x0fNetworkAnalyzer\x12O\n\x0bSolveMatrix\x12\x1b.networkanalysis.MatrixData\x1a!.networkanalysis.SolutionResponse\"\x00\x42\x46ZDgithub.com/DrC0ns0le/net-perf/pkg/pb/networkanalysis;networkanalysisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.networkanalysis.networkanalysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDgithub.com/DrC0ns0le/net-perf/pkg/pb/networkanalysis;networkanalysis'
  _globals['_MATRIXDATA']._serialized_start=64
  _globals['_MATRIXDATA']._serialized_end=170
  _globals['_SOLUTIONRESPONSE']._serialized_start=172
  _globals['_SOLUTIONRESPONSE']._serialized_end=240
  _globals['_NETWORKANALYZER']._serialized_start=242
  _globals['_NETWORKANALYZER']._serialized_end=340
# @@protoc_insertion_point(module_scope)
